services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_app
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./database/database.sqlite:/var/www/database/database.sqlite:rw
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/database/database.sqlite

  webserver:
    image: nginx:alpine
    container_name: nginx_web
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge